---
title: "COBS for brainspan data"
output: html_document
date: "2023-11-13"
---


```{r, echo=F, message=F, warning=F, results=F}
######## replicating the results 
###https://github.com/linnykos/covarianceSelection
rm(list=ls())
set.seed(123)

# install dependent packages 

#install.packages("doMC", repos="http://R-Forge.R-project.org")
library("doMC")

# if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("org.Hs.eg.db")
library("org.Hs.eg.db")

#download gz file to local folder and install https://cran.r-project.org/src/contrib/Archive/dequer/
library(dequer)


library("devtools")
devtools::install_github("linnylin92/covarianceSelection", subdir = "covarianceSelection")

```



```{r, echo=F, message=F, warning=F, eval=F}
# step0_loading.R  https://github.com/linnykos/covarianceSelection/blob/master/main/step0_loading.R
# step0_loading.R loads the BrainSpan dataset and TADA dataset (i.e., matching the genes in both datasets, resolving gene synonyms, removing genes not expressed in the brain).

#if(verbose) print("Start of step 0: Loading")

#format the brainspan dataset
#load("../../raw_data/newGenexp.RData")
load("C:/han/Dataset/20231006_PMID_33731968/NIHMS1598069-supplement-Supp_1/newGenexp.RData")
rownames(genexp) <- genexp[,1]
genexp <- genexp[,-1]
genexp <- t(genexp)
genexp <- as.data.frame(genexp) # 1340 x 16947 ? what does row names indicate? 

#determine brain-expressed genes
brain_expression <- covarianceSelection::brain_expression # how these genes are known to be expressed genes????????  
brain_genes <- brain_expression$Gene[brain_expression$Brain_expressed != 'No']
idx <- which(colnames(genexp) %in% brain_genes)
genexp <- genexp[,idx] # 1340 x 14370

############ sample information is in covarianceSelection::brainspan_id


#translate into synonyms
vec <- covarianceSelection::symbol_synonyms(colnames(genexp), verbose = T)
unknown_genes_idx <- which(is.na(vec))
vec <- vec[-unknown_genes_idx]
genexp <- genexp[-unknown_genes_idx] # 1340 x 14238
colnames(genexp) <- vec

#average non-unique genes
genexp <- covarianceSelection:::average_same_columns(genexp) # 1340 x 14246 --> 1340 x 14238

#remove samples from subregions that we don't have a region for
region_subregion <- covarianceSelection::region_subregion
vec <- rownames(genexp)
subregion <- unlist(strsplit(vec,"\\."))[seq(2, length(vec)*4, 4)]
idx <- which(subregion %in% region_subregion$subregion)
genexp <- genexp[idx,] # 1294 x 14249 --> 1294 x 14238 

################
# explore the notations in row names 
#sample_names=rownames(genexp)
#comma_position=gregexpr(".", sample_names[1])
#sample_names[grepl("VFC",sample_names)] # find samples having "VFC"
################

####

#load tada dataset
tada <- covarianceSelection::tada

#match the order in both datasets
idx <- which(colnames(genexp) %in% tada$Gene)
genexp <- genexp[,idx] # 1294 x 13964  --> 1294 x 13699 

idx <- which(tada$Gene %in% colnames(genexp))
tada <- tada[idx,] # 13964 genes  --> 13699 genes 
idx <- covarianceSelection::matching(tada$Gene, colnames(genexp))
genexp <- genexp[,idx]  # 1294 x 13699 

dat_list <- covarianceSelection::extractor(genexp) # 212 partitions
dat_list <- lapply(dat_list, as.matrix, drop = F)

# remove partitions too small
idx <- which(sapply(dat_list, function(x){ifelse(nrow(x) >= 5, T, F)}))
dat_list <- dat_list[idx] # 125 partitions
dat_list <- lapply(dat_list, scale, scale = F)

#if(verbose) print(paste0("Dimension of genexp is: ", paste0(dim(genexp), collapse = ", ")))

#cleanup
rm(list = c("brain_expression", "brain_genes", "idx", "vec", "region_subregion",
            "subregion", "genexp", "unknown_genes_idx"))

#save.image(file = paste0(save_filepath, "/step0_loading", filepath_suffix, ".RData"))

```



```{r, echo=F, message=F, warning=F, eval=F}
# step1_screening.R screens the genes according to Liu et al. (2015). This is reported in Section 6.1.
# https://github.com/linnykos/covarianceSelection/blob/master/main/step1_screening.R
p_thres_screening <- 0.01 
p_primary <- 0.1
num_genes <- 3500
verbose=T

###

if(verbose) print(paste0(Sys.time(), "Start of step 1: Screening"))

selected_idx <- grep("PFC\\.[3-5]", names(dat_list))
dat_pfc35 <- do.call(rbind, dat_list[selected_idx]) # 107 x 13964  --> 10 x 13699

screening_res <- covarianceSelection::screen(dat_pfc35, pv = tada$pval.TADA, p_thres = p_thres_screening, 
                                             num_genes = num_genes)

# 265 primary, 3235 secondary, total of 3500

# reorder which genes are primary and which are secondary
all_idx <- sort(unique(c(screening_res$primary, screening_res$secondary)))
screening_res$primary <- all_idx[which(tada$pval.TADA[all_idx] < p_primary)]
screening_res$secondary <- setdiff(all_idx, screening_res$primary)

# apply the new gene list
for(i in 1:length(dat_list)){
  dat_list[[i]] <- dat_list[[i]][,c(screening_res$primary, screening_res$secondary)]
}
tada <- tada[c(screening_res$primary, screening_res$secondary),]
                
if(verbose) print(paste0("Dimension of dat_list is: ", unique(sapply(dat_list, ncol)), collapse = ", "))

rm(list = c("selected_idx", "dat_pfc35", "i"))

#save.image(file = paste0(save_filepath, "/step1_screening", filepath_suffix, ".RData"))
```


```{r, echo=F, message=F, warning=F, eval=F}
# https://github.com/linnykos/covarianceSelection/blob/master/main/step2_nodawn_analysis.R
# step2_nodawn_analysis.R detects the risk genes only based on the TADA dataset.

fdr_cutoff_alt <- 0.1
verbose=T

if(verbose) print(paste0(Sys.time(), "Start of step 2: No DAWN analysis"))

genes_nodawn <- sort(as.character(tada[which(tada$qvalue <= fdr_cutoff_alt),"Gene"]))

#save.image(file = paste0(save_filepath, "/step2_nodawn_analysis", filepath_suffix, ".RData"))
```


```{r echo=F, message=F, warning=F, eval=F}
# step3_pfc35_analysis.R implicates risk genes in the DAWN framework using the Window 1B partitions. This is reported in Section 6.4.
# https://github.com/linnykos/covarianceSelection/blob/master/main/step3_pfc35_analysis.R
fdr_cutoff <- 0.01
pthres <- 0.05
verbose=T



#####
set.seed(10)
if(verbose) print(paste0(Sys.time(), "Start of step 3: Naive analysis"))

selected_idx <- grep("PFC\\.[3-5]", names(dat_list))
dat_pfc35 <- do.call(rbind, dat_list[selected_idx]) # 107 x 3065
dat_pfc35 <- scale(dat_pfc35, scale = F)

# estimate graphical model on PFC35 using cross-validated lasso for neighborhood selection
# res <- covarianceSelection::graphicalModel_range(dat_pfc35, 1:length(screening_res$primary), 
#                                                  lambda_min = 0.01, lambda_max = 0.35, 
#                                                  lambda_length = 30, verbose = T) 
# save.image(file = paste0(save_filepath, "/step3_pfc35_analysis", filepath_suffix, ".RData"))
# 
# scale_vec_pfc35 <- sapply(res, function(x){covarianceSelection::compute_scale_free(as.matrix(x$adj_mat))})
# edges_vec_pfc35 <- sapply(res, function(x){sum(as.matrix(x$adj_mat))/2})
# # idx <- which.max(scale_vec_pfc35)
# idx <- 27
# adj_pfc35 <- as.matrix(res[[idx]]$adj_mat)

res <- covarianceSelection::graphicalModel(dat_pfc35, primary_idx = 1:length(screening_res$primary), lambda = seq(0.05, 0.1, length.out = 15)[1])
adj_pfc35 <- as.matrix(res$adj_mat)
stopifnot(all(dim(adj_pfc35) == nrow(tada)))

# run the HMRF
set.seed(10)
seedindex <- rep(0, ncol(adj_pfc35))
seedindex[which(tada$dn.LoF >= 3)] <- 1

if(verbose) print(paste0(Sys.time(), ": HMRF"))
set.seed(10)
hmrf_pfc35 <- covarianceSelection::hmrf(tada$pval.TADA, adj_pfc35, seedindex, pthres = pthres)
report_pfc35 <- covarianceSelection::report_results(tada$Gene, 1-hmrf_pfc35$post, tada$pval.TADA, hmrf_pfc35$Iupdate)
genes_pfc35 <- sort(as.character(report_pfc35$Gene[which(report_pfc35$FDR <= fdr_cutoff)]))

adj_pfc35 <- Matrix::Matrix(adj_pfc35, sparse = T)

rm(list = c("dat_pfc35", "seedindex", "idx", "res", "selected_idx"))

#save.image(file = paste0(save_filepath, "/step3_pfc35_analysis", filepath_suffix, ".RData"))

########################

 #plot(exp(seq(log(0.01), log(0.35), length.out = length(scale_vec_pfc35))), scale_vec_pfc35)
```


```{r, echo=F, message=F, warning=F, eval=F}
# step4_subjectselection.R uses COBS and is the most computational-intensive part of our procedure. This selects the 24 partitions in BrainSpan that we report in our paper. This is reported in Section 6.2.
# https://github.com/linnykos/covarianceSelection/blob/master/main/step4_subjectselection.R
trials <- 100
prob_val <- 1-1e-5
stepdown_alpha <- 0.1

if(verbose) print(paste0(Sys.time(), "Start of step 5: Subject selection"))

##### it takes about 15 hours to run 
set.seed(10)
stepdown_res <- covarianceSelection::stepdown(dat_list, trials = trials, alpha = stepdown_alpha, return_pvalue = F,
                                              prob = prob_val, verbose = T, cores = ncores)

#save.image(file = paste0(save_filepath, "/step4_subjectselection", filepath_suffix, ".RData"))
#save.image(file="C:/han/Dataset/20231006_PMID_33731968/NIHMS1598069-supplement-Supp_1/stepdown_res.RData")
```


```{r, echo=F, message=F, warning=F, eval=F}
#step5_our_analysis.R implicates risk genes in the DAWN framework using our 24 partitions selected by COBS. This is reported in Section 6.4.
# https://github.com/linnykos/covarianceSelection/blob/master/main/step5_our_analysis.R

load("C:/han/Dataset/20231006_PMID_33731968/NIHMS1598069-supplement-Supp_1/stepdown_res.RData") # load results in step 4

gamma_threshold <- 0.95

if(verbose) print(paste0(Sys.time(), "Start of step 6: Our data analysis"))

n <- length(dat_list)
g_selected <- igraph::graph.empty(n = n, directed = F)
combn_mat <- utils::combn(length(dat_list), 2)
g_selected <- igraph::add_edges(g_selected, edges = combn_mat[,stepdown_res$null_idx])

# construct the core set
selected_idx <- grep("PFC\\.[3-5]", names(dat_list))
g_sub <- igraph::induced_subgraph(g_selected, selected_idx)
core_set <- selected_idx[covarianceSelection::clique_selection(g_sub, threshold = gamma_threshold)[[1]]]
idx_our <- covarianceSelection::clique_selection(g_selected, threshold = gamma_threshold, target_idx = core_set)
idx_our <- idx_our[[1]]

dat_our <- do.call(rbind, dat_list[idx_our])
dat_our <- scale(dat_our, scale = F)

res <- covarianceSelection::graphicalModel(dat_our, primary_idx = 1:length(screening_res$primary), 
                                           lambda = seq(0.05, 0.1, length.out = 15)[5])
adj_our <- as.matrix(res$adj_mat)

# run the HMRF
set.seed(10)
seedindex <- rep( 0, ncol(adj_our))
seedindex[which(tada$dn.LoF >= 3)] <- 1

if(verbose) print(paste0(Sys.time(), ": HMRF"))
set.seed(10)
hmrf_our <- covarianceSelection::hmrf(tada$pval.TADA, adj_our, seedindex, pthres = pthres) 
report_our <- covarianceSelection::report_results(tada$Gene, 1-hmrf_our$post, tada$pval.TADA, hmrf_our$Iupdate)
genes_our <- sort(as.character(report_our$Gene[which(report_our$FDR <= fdr_cutoff)]))

adj_our <- Matrix::Matrix(adj_our, sparse = T)

rm(list = c("dat_our", "seedindex", "res", "combn_mat", "n", "g_selected", "g_sub", "selected_idx", "core_set"))

#save.image(file = paste0(save_filepath, "/step5_ourdata_analysis", filepath_suffix, ".RData"))
```





```{r, echo=F, message=F, warning=F, eval=F}
# step6_our_analysis_robustness.R performs the robustness analysis. This is reported in Section 6.4.
# https://github.com/linnykos/covarianceSelection/blob/master/main/step6_our_analysis_robustness.R
gamma_vec <- seq(0.85, 0.97, length.out = 13)

if(verbose) print(paste0(Sys.time(), "Start of step 6: Analyzing robustness of our methods"))

genes_list_multigamma <- sapply(gamma_vec, function(gamma){
  n <- length(dat_list)
  g_selected <- igraph::graph.empty(n = n, directed = F)
  combn_mat <- utils::combn(length(dat_list), 2)
  g_selected <- igraph::add_edges(g_selected, edges = combn_mat[,stepdown_res$null_idx])
  
  # construct the core set
  selected_idx <- grep("PFC\\.[3-5]", names(dat_list))
  g_sub <- igraph::induced_subgraph(g_selected, selected_idx)
  core_set <- selected_idx[covarianceSelection::clique_selection(g_sub, threshold = gamma)[[1]]]
  idx_our <- covarianceSelection::clique_selection(g_selected, threshold = gamma, 
                                                   target_idx = core_set, verbose = T, max_length = 5000)
  idx_our <- idx_our[[1]]
  
  dat_our <- do.call(rbind, dat_list[idx_our])
  dat_our <- scale(dat_our, scale = F)
  
  res <- covarianceSelection::graphicalModel(dat_our, primary_idx = 1:length(screening_res$primary), lambda = seq(0.05, 0.1, length.out = 15)[5])
  adj_our <- as.matrix(res$adj_mat)
  
  # run the HMRF
  set.seed(10)
  seedindex <- rep(0, ncol(adj_our))
  seedindex[which(tada$dn.LoF >= 3)] <- 1
  
  set.seed(10)
  hmrf_our <- covarianceSelection::hmrf(tada$pval.TADA, adj_our, seedindex, pthres = pthres)
  report_our <- covarianceSelection::report_results(tada$Gene, 1-hmrf_our$post, tada$pval.TADA, hmrf_our$Iupdate)
  sort(as.character(report_our$Gene[which(report_our$FDR <= fdr_cutoff)]))
})

genes_our_intersect <- intersect(genes_list_multigamma[[1]], genes_list_multigamma[[2]])
for(i in 3:length(genes_list_multigamma)){
  genes_our_intersect <- intersect(genes_our_intersect, genes_list_multigamma[[3]])
}

#save.image(file = paste0(save_filepath, "/step6_our_analysis_robustness", filepath_suffix, ".RData"))
```



```{r, echo=F, message=F, warning=F}
# https://github.com/linnykos/covarianceSelection/blob/master/main/step7_goodness.R

if(verbose) print(paste0(Sys.time(), "Start of step 7: Computing goodness of fit"))
prob_goodness <- seq(1-1e-5, 1-1e-4, length.out = 5)[2]

goodness_our <- covarianceSelection::goodness_of_fit(dat_list[idx_our], permutations = 250, trials = 100, verbose = T, prob = prob_goodness)

if(verbose) print(paste0(Sys.time(), "Finished ours"))
save.image(file = paste0(save_filepath, "/step7_goodness", filepath_suffix, ".RData"))

##

selected_idx <- grep("PFC\\.[3-5]", names(dat_list))
set.seed(10)
goodness_pfc35 <- covarianceSelection::goodness_of_fit(dat_list[selected_idx], permutations = 250, trials = 100, 
                                                       verbose = T, prob = prob_goodness)

if(verbose) print(paste0(Sys.time(), "Finished PFC35"))
save.image(file = paste0(save_filepath, "/step7_goodness", filepath_suffix, ".RData"))

##

set.seed(10)
prob_goodness <- 1-1e-6
goodness_all <- covarianceSelection::goodness_of_fit(dat_list, permutations = 250, trials = 100, prob = prob_goodness, 
                                                     verbose = T)

if(verbose) print(paste0(Sys.time(), "Finished all"))
rm(list = c("prob_goodness"))

#save.image(file = paste0(save_filepath, "/step7_goodness", filepath_suffix, ".RData"))
```


```{r, echo=F, message=F, warning=F, eval=F}
if(verbose) print(paste0(Sys.time(), "Start of step 8: Compiling the results"))

validated_genes <- covarianceSelection::validated_genes$Gene

num_pfc35 <- length(intersect(genes_pfc35, validated_genes))  
num_nodawn <- length(intersect(genes_nodawn, validated_genes)) 
num_our <- length(intersect(genes_our, validated_genes)) 
num_intersect <- length(intersect(genes_our_intersect, validated_genes)) 

# output some summaries
c(num_pfc35, num_nodawn, num_our, num_intersect)
c(length(genes_pfc35), length(genes_nodawn), length(genes_our), length(genes_our_intersect))
c(sum(as.matrix(adj_pfc35))/2, sum(as.matrix(adj_our))/2)
c(covarianceSelection::compute_scale_free(as.matrix(adj_pfc35)), covarianceSelection::compute_scale_free(as.matrix(adj_our)))

cbind(names(dat_list[idx_our]), sapply(dat_list[idx_our], nrow))
covarianceSelection::binning(names(dat_list)[idx_our])

# computing eigen decompositions for the figure diagnostics
eigen_pfc35 <- eigen(as.matrix(adj_pfc35))
eigen_our <- eigen(as.matrix(adj_our))

#save.image(file = paste0(save_filepath, "/step8_results", filepath_suffix, ".RData"))
```


```{r, echo=F, message=F, warning=F, eval=F}
# https://github.com/linnykos/covarianceSelection/blob/master/main/step9_figures.R
color_palatte <- c(rgb(245, 234, 204, maxColorValue = 255), #yellow
                   rgb(189, 57, 60, maxColorValue = 255)) #red

# plot the graph
n <- length(dat_list)
g_selected <- igraph::graph.empty(n = n, directed = F)
combn_mat <- utils::combn(length(dat_list), 2)
g_selected <- igraph::add_edges(g_selected, edges = combn_mat[,stepdown_res$null_idx])

tmp <- rep(1, igraph::vcount(g_selected)); tmp[idx_our] <- 2
igraph::V(g_selected)$color <- color_palatte[tmp]
igraph::V(g_selected)$size <- c(5,10)[tmp]

# first construct 3 sets of nodes: first is our selected idx, the second is all the other nodes in the
## the giant component, and the third is all the remaining nodes
n <- igraph::vcount(g_selected)
idx1 <- intersect(idx_our, grep("PFC\\.[3-5]", names(dat_list)))
idx2 <- sort(idx_our)
idx2 <- setdiff(idx2, idx1)
tmp <-  igraph::components(g_selected)
idx3 <- sort(setdiff(which(tmp$membership == 1), c(idx1,idx2)))
adj_tmp <- as.matrix(igraph::as_adjacency_matrix(g_selected))
adj_tmp <- adj_tmp[c(idx1, idx2, idx3), c(idx1, idx2, idx3)]
diag(adj_tmp) <- 1

.rotate = function(a) { t(a[nrow(a):1,]) } 

png("../figures/figure_9.png", height = 1000, width = 2000, units = "px", res = 300)
par(mar = c(0,0,3,0), mfrow = c(1,2))
set.seed(10)
igraph::plot.igraph(g_selected, vertex.label = NA, main = "Full graph")

par(mar = c(3,3,3,0.5))
# next plot the adjacency matrix
image(.rotate(adj_tmp), asp = T, col = color_palatte, breaks = c(-.5,.5,1.5), xaxt = "n", yaxt = "n",
      xlab = "", ylab = "", main = "Adjacency matrix (subgraph)", axes = F)
title(ylab = "Index locations", mgp = c(1,1,0))
title(xlab = "Index locations", mgp = c(1,1,0))

# put in dashed lines
x_width <- length(idx_our)/nrow(adj_tmp)
y_height <- 1 - x_width
lines(rep(x_width, 2), c(1,1-x_width), lwd = 2, lty = 2)
lines(c(0,x_width), rep(y_height, 2), lwd = 2, lty = 2)
graphics.off()

############################################

png("../figures/figure_10b.png", height = 1300, width = 1150, units = "px", res = 300)
par(mar = c(4,4,4,1))
goodness_our <- goodness_list[[2]]
plot(sort(goodness_our), seq(0,1,length.out = length(goodness_our)), asp = T, xlab = "Theoretical quantiles",
     pch = 16,
     ylab = "Observed quantiles", main = "QQ-plot based on data\nfrom selected partitions")
lines(c(0,1),c(0,1), col = "red", lty = 2)
points(sort(goodness_our), seq(0,1,length.out = length(goodness_our)), pch = 16)
graphics.off()

##############################################

png("../figures/figure_2.png", height = 1300, width = 2300, units = "px", res = 300)
par(mar = c(4,4,4,1), mfrow = c(1,2))
plot(sort(goodness_pfc35), seq(0,1,length.out = length(goodness_pfc35)), asp = T, xlab = "Theoretical quantiles",
     pch = 16,
     ylab = "Observed quantiles", main = "QQ-plot based on partitions\nfrom only Window 1B")
lines(c(0,1),c(0,1), col = "red", lty = 2)
points(sort(goodness_pfc35), seq(0,1,length.out = length(goodness_pfc35)), pch = 16)

plot(sort(goodness_all), seq(0,1,length.out = length(goodness_all)), asp = T, xlab = "Theoretical quantiles",
     pch = 16,
     ylab = "Observed quantiles", main = "QQ-plot based on all partitions")
lines(c(0,1),c(0,1), col = "red", lty = 2)
points(sort(goodness_all), seq(0,1,length.out = length(goodness_all)), pch = 16)
graphics.off()

#########################################

validated_idx <- which(colnames(dat_list[[1]]) %in% validated_genes)
nodawn_idx <- which(colnames(dat_list[[1]]) %in% genes_nodawn)
validated_idx <- setdiff(validated_idx, nodawn_idx)
k_vec <- 1:10

res_mat1 <- sapply(k_vec, function(k){
   val1 <- covarianceSelection::compute_mst_distance(as.matrix(adj_our), validated_idx, nodawn_idx, k)
   val2 <- covarianceSelection::compute_mst_distance(as.matrix(adj_pfc35), validated_idx, nodawn_idx, k)
   
   c(val1, val2)
})

k_vec <- 1:10
res_mat2 <- sapply(k_vec, function(k){
   val1 <- covarianceSelection::compute_graph_root_distance(eigen_our$vectors, validated_idx, nodawn_idx, k)
   val2 <- covarianceSelection::compute_graph_root_distance(eigen_pfc35$vectors, validated_idx, nodawn_idx, k)
   
   c(val1, val2)
})

(res_mat2[2,]-res_mat2[1,])/res_mat2[1,]

png("../figures/appendix_9.png", height = 1300, width = 2300, units = "px", res = 300)
par(mar = c(4,4,4,1), mfrow = c(1,2))
plot(NA, xlim = range(k_vec), ylim = range(res_mat1), main = "Distance from Satterstrom genes to\nDe Rubeis genes: MST",
     xlab = "Number of closeby De Rubeis genes", ylab = "Distance in MST", cex.main = 1)
lines(k_vec, res_mat1[2,], lwd = 2, col = color_palatte[1])
points(k_vec, res_mat1[2,], pch = 21, bg = color_palatte[1])
lines(k_vec, res_mat1[1,], lwd = 2, col = color_palatte[2])
points(k_vec, res_mat1[1,], pch = 16, col = color_palatte[2])
legend("topleft", c("Using Window 1B graph", "Using COBS graph"),
       bty="n", fill=color_palatte, cex = 0.75)

plot(NA, xlim = range(k_vec), ylim = range(res_mat2), main = "Distance from Satterstrom genes to\nDe Rubeis genes: graph root embedding",
     xlab = "Number of closeby De Rubeis genes", ylab = "Distance in graph root embedding", cex.main = 1)
lines(k_vec, res_mat2[2,], lwd = 2, col = color_palatte[1])
points(k_vec, res_mat2[2,], pch = 21, bg = color_palatte[1])
lines(k_vec, res_mat2[1,], lwd = 2, col = color_palatte[2])
points(k_vec, res_mat2[1,], pch = 16, col = color_palatte[2])

legend("topleft", c("Using Window 1B graph", "Using COBS graph"),
       bty="n", fill=color_palatte, cex = 0.75)
graphics.off()

median((res_mat1[2,] - res_mat1[1,])/res_mat1[2,])
median((res_mat2[2,] - res_mat2[1,])/res_mat2[2,])
```
