---
title: "functional enrichment"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2026-05-21"
---



```{r, message=F, warning=F}
rm(list=ls())
set.seed(123)
library(tidyverse)
library(ggplot2)
library(DT)
library(VennDiagram)
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
```



```{r, message=F, warning=F}

result_round1=as_tibble(read.csv(file.path(root, "../DiWangResults/results_20260521/final_risk_gene_pred.csv")))


SFARI_genes=as_tibble(read.csv(file.path(root, "../../../Dataset/SFARI_base/SFARI-Gene_genes_08-19-2024release_09-16-2024export.csv")))
positive_genes=SFARI_genes %>% filter (gene.score=="1") %>% dplyr::select(gene.symbol) %>% pull()
positive_genes=intersect(positive_genes, result_round1$gene)

```



```{r, message=F, warning=F}
# 1. Load the local annotation library
if (!require("org.Hs.eg.db")) install.packages("org.Hs.eg.db")
library(org.Hs.eg.db)

# 2. Clean up version dots if any exist (e.g., ENSG00000000419.12 -> ENSG00000000419)
result_round1$ensembl_string <- gsub("\\..*", "", result_round1$ensembl_string)

# 3. Create the new gene symbol column using 'ENSEMBL' as the keytype
result_round1$gene_symbol <- mapIds(org.Hs.eg.db,
                                         keys = result_round1$ensembl_string,
                                         column = "SYMBOL",
                                         keytype = "ENSEMBL",
                                         multiVals = "first")

# 4. Optional: Relocate the column next to ensembl_string for easy reading
if (require("dplyr")) {
  result_round1 <- result_round1 %>% relocate(gene_symbol, .after = ensembl_string)
}
```



## gprofiler 



### deep motif genes 


```{r, message=F, warning=F}
score_cutoff=0.8
top_genes=result_round1 %>% filter(score_mean>score_cutoff) %>% dplyr::select(gene_symbol) %>% pull

#install.packages("gprofiler2")
library(gprofiler2)   ### https://biit.cs.ut.ee/gprofiler/page/r
gostres <- gost(query = top_genes,
organism = "hsapiens", significant = TRUE, correction_method = "bonferroni")

# output the enrichment 
gostres$result %>% 
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

length(unique(gostres$result$term_name))
```




```{r, message=F, warning=F}

p <- gostplot(gostres, capped = F, interactive = F)
p
pp <- publish_gostplot(p, highlight_terms = c("HP:0000729", "HP:0025783", "HP:0000734", "HP:5200241", "GO:0007399"), 
                       width = NA, height = NA, filename = NULL )


```