---
title: "score distribution"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2026-04-13"
---

```{r, message=F, warning=F}
rm(list=ls())
set.seed(123)
library(tidyverse)
library(ggplot2)
library(DT)
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
```




```{r, message=F, warning=F, eval=F}
Deep_MOTIFs_result=as_tibble(read.csv(file.path(root, "../DiWangResults/results_20260330/data/data/mean_run/deep_motifs_outputs/full_scores_summary.csv")))


library(biomaRt)

# 1. You already did this, but just to be sure:
mart <- useMart("ensembl", 
                dataset = "hsapiens_gene_ensembl", 
                host = "https://useast.ensembl.org")

# 2. THE MISSING STEP: Actually pull the data into the 'mapping' object
mapping <- getBM(
  attributes = c("ensembl_peptide_id", "hgnc_symbol"),
  filters = "ensembl_peptide_id",
  values = Deep_MOTIFs_result$ensembl_string,
  mart = mart
)

# 3. Now the merge will work:
Deep_MOTIFs_result <- merge(Deep_MOTIFs_result, mapping, 
                            by.x = "ensembl_string", 
                            by.y = "ensembl_peptide_id", 
                            all.x = TRUE)

#saveRDS(Deep_MOTIFs_result, file=file.path(root, "../DiWangResults/results_20260330/data/data/mean_run/deep_motifs_outputs/Deep_MOTIFs_result.RDS"))

```



```{r, message=F, warning=F}
Deep_MOTIFs_result=readRDS(file.path(root, "../DiWangResults/results_20260330/data/data/mean_run/deep_motifs_outputs/Deep_MOTIFs_result.RDS"))
```




## histogram of scores 



```{r, message=F, warning=F}
hist_plot1=ggplot(Deep_MOTIFs_result, aes(x = Deep_MOTIFs_result$forecASD)) +
  geom_histogram(binwidth = 0.1, fill = "blue", color = "black", aes(y = ..count..)) +
  stat_bin(binwidth = 0.1, geom = "text", aes(label = ..count..), vjust = -0.5, color = "red") +
  #geom_density(color = "darkorange", size = .2) +
  labs(title = "Histogram of Deep-MOTIFs scores", x = "Deep-MOTIFs score", y = "Number of genes")+
  geom_vline(xintercept = 0.5, color = "green", linetype = "dashed", size = 1)+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 
hist_plot1
```




## implicated risk genes 


```{r, message=F, warning=F}
score_cutoff=0.5


SFARI_genes=as_tibble(read.csv(file.path(root, "../../../Dataset/SFARI_base/SFARI-Gene_genes_08-19-2024release_09-16-2024export.csv")))
positive_genes=SFARI_genes %>% filter (gene.score=="1") %>% dplyr::select(gene.symbol) %>% pull()


motifs_genes=Deep_MOTIFs_result %>% filter(forecASD>score_cutoff) %>% dplyr::select(hgnc_symbol) %>% pull()



SFARI_score_for_motif_genes <- ifelse(
  motifs_genes %in% SFARI_genes$gene.symbol,
  SFARI_genes$gene.score[match(motifs_genes, SFARI_genes$gene.symbol)],
  NA
)

Deep_MOTIFs_result %>% filter(forecASD>score_cutoff) %>% dplyr::select(ensembl_string, forecASD, hgnc_symbol)%>% mutate(SFARI_score=SFARI_score_for_motif_genes) %>% arrange(desc(forecASD)) %>% 
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


SFARI_table=table(SFARI_score_for_motif_genes, useNA = "ifany")

SFARI_table

```