---
title: "score distribution"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2026-05-21"
---



```{r, message=F, warning=F}
rm(list=ls())
set.seed(123)
library(tidyverse)
library(ggplot2)
library(DT)
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
```




```{r, message=F, warning=F, eval=T}
Deep_MOTIFs_result=as_tibble(read.csv(file.path(root, "../DiWangResults/results_20260521/final_risk_gene_pred.csv")))

```




```{r, message=F, warning=F}
# 1. Load the local annotation library
if (!require("org.Hs.eg.db")) install.packages("org.Hs.eg.db")
library(org.Hs.eg.db)

# 2. Clean up version dots if any exist (e.g., ENSG00000000419.12 -> ENSG00000000419)
Deep_MOTIFs_result$ensembl_string <- gsub("\\..*", "", Deep_MOTIFs_result$ensembl_string)

# 3. Create the new gene symbol column using 'ENSEMBL' as the keytype
Deep_MOTIFs_result$gene_symbol <- mapIds(org.Hs.eg.db,
                                         keys = Deep_MOTIFs_result$ensembl_string,
                                         column = "SYMBOL",
                                         keytype = "ENSEMBL",
                                         multiVals = "first")

# 4. Optional: Relocate the column next to ensembl_string for easy reading
if (require("dplyr")) {
  Deep_MOTIFs_result <- Deep_MOTIFs_result %>% relocate(gene_symbol, .after = ensembl_string)
}
```




## histogram of scores 



```{r, message=F, warning=F}
hist_plot1=ggplot(Deep_MOTIFs_result, aes(x = Deep_MOTIFs_result$score_mean)) +
  geom_histogram(binwidth = 0.1, fill = "blue", color = "black", aes(y = ..count..)) +
  stat_bin(binwidth = 0.1, geom = "text", aes(label = ..count..), vjust = -0.5, color = "red") +
  #geom_density(color = "darkorange", size = .2) +
  labs(title = "Histogram of Deep-MOTIFs scores", x = "Deep-MOTIFs score", y = "Number of genes")+
  geom_vline(xintercept = 0.5, color = "green", linetype = "dashed", size = 1)+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 
hist_plot1
```




## implicated risk genes 


```{r, message=F, warning=F}
score_cutoff=0.8


SFARI_genes=as_tibble(read.csv(file.path(root, "../../../Dataset/SFARI_base/SFARI-Gene_genes_08-19-2024release_09-16-2024export.csv")))
positive_genes=SFARI_genes %>% filter (gene.score=="1") %>% dplyr::select(gene.symbol) %>% pull()


motifs_genes=Deep_MOTIFs_result %>% filter(score_mean>score_cutoff) %>% dplyr::select(gene_symbol) %>% pull()



SFARI_score_for_motif_genes <- ifelse(
  motifs_genes %in% SFARI_genes$gene.symbol,
  SFARI_genes$gene.score[match(motifs_genes, SFARI_genes$gene.symbol)],
  NA
)

Deep_MOTIFs_result %>% filter(score_mean>score_cutoff) %>% dplyr::select(ensembl_string, score_mean, gene_symbol)%>% mutate(SFARI_score=SFARI_score_for_motif_genes) %>% arrange(desc(score_mean)) %>% 
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


SFARI_table=table(SFARI_score_for_motif_genes, useNA = "ifany")

SFARI_table

```




```{r, message=F, warning=F}
 
 # Create data frame
df <- data.frame(
  score = c( "3", "NA"),
  count = as.numeric(SFARI_table)
)

# Sort descending by count (important for label matching pie slices)
df <- df %>%
  arrange(desc(score)) %>%
  mutate(
    ypos = cumsum(count) - count / 2
  )

# Create pie chart with count labels
pie_fig1=ggplot(df, aes(x = "", y = count, fill = score)) +
  geom_col(width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(y = ypos, label = count), color = "black", size = 5) +
  labs(title = "Deep-MOTIFs Genes", fill = "SFARI score") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  theme(legend.position = "right")
 pie_fig1
```