---
title: "3/19 2025"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2025-03-19"
---



```{r, message=F, warning=F}
rm(list=ls())
set.seed(123)
library(tidyverse)
library(ggplot2)
library(DT)
library(VennDiagram)
library(rprojroot)
library(biomaRt)
library(igraph)
root <- rprojroot::find_rstudio_root_file()
```



```{r, message=F, warning=F}
#result_round1=as_tibble(read.csv(file.path(root, "../DiWangResults/ASD_prediction_results/ASD_RISK_PREDICTION_round1.csv"))) # old results 

result_round1=as_tibble(read.csv(file.path(root, "../DiWangResults/results updated_20250303/ASD_RISK_PREDICTION round 1.csv")))
result_round1=result_round1[result_round1['gene'] != 0,]  # remove rows with gene=0
```


```{r, message=F, warning=F}
score_cutoff=0.5
top_genes=result_round1 %>% filter(RISK_PROBABILITY_FUSION>score_cutoff) %>% dplyr::select(gene_gencodeV33) %>% pull

#library(biomaRt)
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl", host = "https://grch37.ensembl.org")
# Define function to split queries
query_genes_in_batches <- function(genes, batch_size = 50) {
  results <- list()
  for (i in seq(1, length(genes), by = batch_size)) {
    batch <- genes[i:min(i + batch_size - 1, length(genes))]
    cat("Querying batch:", i, "to", min(i + batch_size - 1, length(genes)), "\n")
    
    batch_result <- tryCatch({
      getBM(attributes = c("hgnc_symbol", "ensembl_gene_id", "ensembl_peptide_id"),
            filters = "hgnc_symbol",
            values = batch,
            mart = ensembl)
    }, error = function(e) {
      cat("Error in batch query:", e$message, "\n")
      return(NULL)
    })
    
    results <- append(results, list(batch_result))
  }
  return(do.call(rbind, results))
}

# Run the batch query
top_genes_info <- query_genes_in_batches(top_genes, batch_size = 1000)
#write.csv(jack_fu_gene_info, file="C:\\Users\\hans\\OneDrive - Marquette University\\AI_for_Autism\\jack_fu_gene_info.csv")

```




```{r, message=F, warning=F}
############# load string protein interaction data 
load("C:\\han\\Projects\\IntegratePPI\\tmp01_STRING_graph.Rdata")  # this is the protein interaction with score>400


protein1_gene <- top_genes_info$hgnc_symbol[match(string.keep$protein1, top_genes_info$ensembl_peptide_id)]
protein2_gene <- top_genes_info$hgnc_symbol[match(string.keep$protein2, top_genes_info$ensembl_peptide_id)]

top_genes_interaction=data.frame(protein1_gene, protein2_gene) %>% drop_na()  # string interactions for top genes 

#library(igraph)
# Create the graph from the edge list (gene interactions)
g <- graph_from_data_frame(top_genes_interaction, directed = FALSE)

# Simplify the graph by removing multi-edges and loops (if any)
g <- igraph::simplify(g, remove.multiple = TRUE, remove.loops = TRUE)

# Compute community structure
fg_community <- fastgreedy.community(g)

# Print community structure
#print(fg_community)

# Get membership (which community each gene belongs to)
#membership(fg_community)

# Plot the network with communities
plot(fg_community, g, vertex.size = 5, vertex.label = NA,  main = "Gene module communities")
```




  
```{r, message=F, warning=F, eval=F}

# Extract the membership of each vertex
membership_vector <- membership(fg_community)

# Print the membership of each vertex
print(membership_vector)

# Group the vertices by community
communities <- split(V(g)$name, membership_vector)

for (i in seq_along(fg_community)) {
  # Extract the subgraph of the current community
  subgraph <- induced_subgraph(g, which(membership(fg_community) == i))
  
  # Get edge list
  edges <- as.data.frame(get.edgelist(subgraph))
  
  # Create file name for the community
  file_name <- paste0("C:\\han\\Projects\\2025_02_deep_motifs\\results\\community_", i, ".csv")
  
  # Write edge list to CSV file
  write.csv(edges, file_name, row.names = FALSE, col.names = c("Source", "Target"))
}

```