---
title: "functional enrichment"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2025-03-18"
---


```{r, message=F, warning=F}
rm(list=ls())
set.seed(123)
library(tidyverse)
library(ggplot2)
library(DT)
library(VennDiagram)
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
```





```{r, message=F, warning=F}
#result_round1=as_tibble(read.csv(file.path(root, "../DiWangResults/ASD_prediction_results/ASD_RISK_PREDICTION_round1.csv"))) # old results 

result_round1=as_tibble(read.csv(file.path(root, "../DiWangResults/results updated_20250303/ASD_RISK_PREDICTION round 1.csv")))
result_round1=result_round1[result_round1['gene'] != 0,]  # remove rows with gene=0


SFARI_genes=as_tibble(read.csv(file.path(root, "../../../Dataset/SFARI_base/SFARI-Gene_genes_08-19-2024release_09-16-2024export.csv")))
positive_genes=SFARI_genes %>% filter (gene.score=="1") %>% dplyr::select(gene.symbol) %>% pull()
positive_genes=intersect(positive_genes, result_round1$gene)

```


## gprofiler 



### deep motif genes 


```{r, message=F, warning=F}
score_cutoff=0.5
top_genes=result_round1 %>% filter(RISK_PROBABILITY_FUSION>score_cutoff) %>% dplyr::select(gene_gencodeV33) %>% pull

#install.packages("gprofiler2")
library(gprofiler2)   ### https://biit.cs.ut.ee/gprofiler/page/r
gostres <- gost(query = top_genes,
organism = "hsapiens", significant = TRUE, correction_method = "bonferroni")

# output the enrichment 
gostres$result %>% 
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

length(unique(gostres$result$term_name))
```

* for 447 Deep-MOTIFs genes, there are 2160 significant enriched items. 



```{r, message=F, warning=F}

p <- gostplot(gostres, capped = F, interactive = F)
p
pp <- publish_gostplot(p, highlight_terms = c("HP:0000729", "HP:0025783", "HP:0000734", "HP:5200241", "GO:0007399"), 
                       width = NA, height = NA, filename = NULL )


```



### motif & SFARI genes 



```{r, message=F, warning=F}
#install.packages("gprofiler2")
library(gprofiler2)   ### https://biit.cs.ut.ee/gprofiler/page/r
gostres2 <- gost(query = list("Deep-MOTIFs genes"=top_genes, "SFARI genes"=positive_genes), 
organism = "hsapiens", significant = TRUE, correction_method = "bonferroni")
dim(gostres2$result)
length(unique(gostres2$result$term_name))

```


```{r, message=F, warning=F}
# output the enrichment results 
#install.packages("writexl")  # if not already installed
library(writexl)

df <- gostres2$result
df[] <- lapply(df, function(x) if (is.list(x)) sapply(x, toString) else x)

#write_xlsx(df, "C:\\Users\\hans\\OneDrive - Marquette University\\AI_for_Autism\\supp\\GO_enrichment.xlsx")
```

* in total 2239 significant enrichment items for 447 Deep-MOTIFs genes and 208 SFARI risk genes. 


```{r, message=F, warning=F}
gostplot(gostres2, capped = F, interactive = TRUE)
```




```{r, message=F, warning=F}
pvalue_threshold=0.05
#output_terms=gostres2$result$term_id[gostres2$result$p_value<1e-20]
#publish_gosttable(gostres2, 
#                         highlight_terms = output_terms,
#                        use_colors = TRUE, 
#                        show_columns = c("source", "term_name", "term_size"),
#                        filename = NULL)

highlight_terms=gostres2$result %>% filter(p_value<pvalue_threshold) %>% dplyr::select(term_id, term_name,  query, p_value)
length(highlight_terms)

highlight_terms_motif_term_id=highlight_terms %>% filter(query=="Deep-MOTIFs genes") %>% dplyr::select(term_id)%>% pull()
highlight_terms_sfari_term_id=highlight_terms %>% filter(query=="SFARI genes") %>% dplyr::select(term_id)%>% pull()
common_term_id=intersect(highlight_terms_motif_term_id, highlight_terms_sfari_term_id)
#highlight_terms %>% filter(term_id %in% common_term_id)
length(common_term_id)

```




```{r, message=F, warning=F}
ggplot(highlight_terms %>% filter(term_id %in% common_term_id), aes(x = term_id, y = -log10(p_value), fill = query)) +
  geom_bar(stat = "identity", position = position_dodge()) +
 # coord_flip() +  # Rotate x and y axes
  theme(axis.text.x = element_blank(),           # remove x-axis text
        axis.ticks.x = element_blank(),          # remove x-axis ticks 
        axis.text.y = element_text(size = 15), 
        axis.title.x = element_text(size = 15)   # Font size for y-axis label
        )+
  labs(title = "Comparison of top enriched items for Deep-MOTIFs genes and SFARI genes ", x = "", y = expression(paste(-log[10](p-value))))+
  theme(legend.title = element_blank()# Remove legend title
        )+
   theme(plot.title = element_text(hjust = 0.5, size=12))  #center the title

```




* [reference](https://cran.r-project.org/web/packages/gprofiler2/vignettes/gprofiler2.html#gene-list-functional-enrichment-analysis-with-gost)



```{r, message=F, warning=F}



highlight_terms_wide=highlight_terms%>%  # convert from long format to wide format 
  pivot_wider(
    names_from = query,
    values_from = p_value,
    names_prefix = "pvalue_"
  )
highlight_terms_wide=highlight_terms_wide %>% drop_na()  # remove enriched terms with NA  pvalue from either deep motifs or sfari 

dim(highlight_terms_wide)


highlight_terms_wide <- highlight_terms_wide %>%
  mutate(group = case_when(
    grepl("^GO:", term_id) ~ "GO",
    grepl("^HPA:", term_id) ~ "HPA",
    grepl("^HP:", term_id) ~ "HP",
    grepl("^TF:", term_id) ~ "TF",
    TRUE ~ "Others"
  ))

top10_labels <- highlight_terms_wide %>%
  mutate(min_p = pmin(`pvalue_Deep-MOTIFs genes`, `pvalue_SFARI genes`)) %>%
  arrange(min_p) %>%
  dplyr::slice(1:10)

library(ggrepel)

ggplot(highlight_terms_wide, aes(x = -log10(`pvalue_Deep-MOTIFs genes`), 
                                 y = -log10(`pvalue_SFARI genes`), 
                                 color = group)) +
  geom_point(alpha = 0.6, size = 2) +
  geom_abline(slope = 1, intercept = 0, linetype = "solid", color = "black", size=1) +
  scale_color_manual(values = c(
    "GO" = "goldenrod2", 
   # "HPA" = "purple4", 
   "HPA" = "black",
    "HP" = "990", 
    "TF" = "blue",
    "Others" = "grey70")) +
  geom_text_repel(
    data = top10_labels,
    aes(label = term_name),
    size = 3,
    max.overlaps = Inf
  ) +
  labs(
    title = "",
    x = "-log10(p value): Deep-MOTIFs",
    y = "-log10(p value): SFARI",
    color = "Group"
  ) +
  theme(legend.title = element_blank())+
  theme(plot.title = element_text(hjust = 0.5, size = 12))



```

* each point is one significant GO term 



```{r, message=F, warning=F}
highlight_terms_wide=highlight_terms%>%  # convert from long format to wide format 
  pivot_wider(
    names_from = query,
    values_from = p_value,
    names_prefix = "pvalue_"
  )


highlight_terms_wide %>%
  filter(is.na(`pvalue_Deep-MOTIFs genes`) & !is.na(`pvalue_SFARI genes`)) %>%
  arrange(`pvalue_SFARI genes`) %>%
  mutate(rank = row_number())%>% 
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
length(unique(highlight_terms_wide %>%
  filter(is.na(`pvalue_Deep-MOTIFs genes`) & !is.na(`pvalue_SFARI genes`)) %>% dplyr::select(term_name) %>% pull()))
```




```{r, message=F, warning=F}

highlight_terms_wide %>%
  filter(!is.na(`pvalue_Deep-MOTIFs genes`) & is.na(`pvalue_SFARI genes`)) %>%
  arrange(`pvalue_Deep-MOTIFs genes`) %>%
  mutate(rank = row_number())%>% 
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

#highlight_terms_wide <- highlight_terms_wide %>%
#  mutate(across(where(is.numeric), ~replace_na(., 1)))  # replace NA with 1 

length(unique(highlight_terms_wide %>%
  filter(!is.na(`pvalue_Deep-MOTIFs genes`) & is.na(`pvalue_SFARI genes`)) %>% dplyr::select(term_name) %>% pull()))


```



```{r, message=F, warning=F}
highlight_terms_wide <- highlight_terms_wide %>%
  mutate(group = case_when(
    grepl("^GO:", term_id) ~ "GO",
    grepl("^HPA:", term_id) ~ "HPA",
    grepl("^HP:", term_id) ~ "HP",
    grepl("^TF:", term_id) ~ "TF",
    TRUE ~ "Others"
  ))

top10_labels <- highlight_terms_wide %>%
  mutate(min_p = pmin(`pvalue_Deep-MOTIFs genes`, `pvalue_SFARI genes`)) %>%
  arrange(min_p) %>%
  dplyr::slice(1:10)

library(ggrepel)

highlight_terms_wide$`pvalue_Deep-MOTIFs genes`[is.na(highlight_terms_wide$`pvalue_Deep-MOTIFs genes`)]=1 # replace na p values with 0 
highlight_terms_wide$`pvalue_SFARI genes`[is.na(highlight_terms_wide$`pvalue_SFARI genes`)]=1


gene_set_enrichment=ggplot(highlight_terms_wide, aes(x = -log10(`pvalue_Deep-MOTIFs genes`), 
                                 y = -log10(`pvalue_SFARI genes`), 
                                 color = group)) +
  geom_point(alpha = 0.6, size = 2, shape =16) +
  geom_abline(slope = 1, intercept = 0, linetype = "solid", color = "black", size=1) +
  scale_color_manual(values = c(
    "GO" = "goldenrod2", 
   # "HPA" = "purple4", 
   "HPA" = "black",
    "HP" = "990", 
    "TF" = "blue",
    "Others" = "grey70")) +
  geom_text_repel(
    data = top10_labels,
    aes(x = -log10(`pvalue_Deep-MOTIFs genes`), 
      y = -log10(`pvalue_SFARI genes`),
     label = term_name, 
     color = group
     ),
    size = 5,
    max.overlaps = Inf,
    inherit.aes = FALSE, 
    show.legend = FALSE  # prevent new legend items
  ) +
  labs(
    title = "(B) Functional enrichment between SFARI and Deep-MOTIFs",
    x = "-log10(p value): Deep-MOTIFs",
    y = "-log10(p value): SFARI",
    color = "Group"
  ) +
  theme_minimal() +
  theme(legend.title = element_blank())+
  #theme(plot.title = element_text(hjust = 0.5, size = 12))
  theme(
    #legend.title = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 25),  # Increased from 12 to 16
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    legend.text = element_text(size = 16)
  )
gene_set_enrichment
```


### plot graphs in paper 

```{r, message=F, warning=F}
forecASD_results=as_tibble(read.csv(file.path(root, "../DiWangResults/forecASD_results.csv")))
forecASD_results=forecASD_results[forecASD_results['gene'] != 0,]  # remove rows with gene=0

forecASD_genes= forecASD_results%>% filter(risk.score>score_cutoff) %>% dplyr::select(gene) %>% pull()
motifs_genes=result_round1 %>% filter(RISK_PROBABILITY_FUSION>score_cutoff) %>% dplyr::select(gene) %>% pull()

total_risk_genes=unique(c(forecASD_genes, motifs_genes))
result_round1_sorted=result_round1 %>% arrange(desc(RISK_PROBABILITY_FUSION))
forecASD_results_sorted=forecASD_results %>% arrange(desc(risk.score))

total_risk_genes_rank1 <- match(total_risk_genes, result_round1_sorted$gene)
total_risk_genes_rank2=match(total_risk_genes, forecASD_results_sorted$gene)


# Combine into a data frame
df <- data.frame(
  Gene = total_risk_genes,
  forecASD = total_risk_genes_rank2,
  Deep_MOTIFs = total_risk_genes_rank1
)

# Reshape data for plotting
df_long <- df %>%
  tidyr::pivot_longer(cols = c(forecASD, Deep_MOTIFs), names_to = "Ranking", values_to = "Rank")

# Join df_long with SFARI_genes on gene symbol
df_long=df_long %>% left_join(SFARI_genes %>% dplyr::select(gene.symbol, gene.score), 
            by = c("Gene" = "gene.symbol"))



# Ensure 'Ranking' is a factor to control plot order
df_long$Ranking <- factor(df_long$Ranking, levels = c("forecASD", "Deep_MOTIFs"))

# Convert gene.score to factor with NA as character
df_long$gene.score <- as.character(df_long$gene.score)
df_long$gene.score[is.na(df_long$gene.score)] <- "NA"
df_long$gene.score <- factor(df_long$gene.score, levels = c("1", "2", "3", "NA"))

# Define colors in the same order
gene.score_colors <- c("1" = "#E41A1C", "2" = "blue", "3" = "#4DAF4A", "NA" = "grey70")

# Plot
ranking_change <- ggplot(df_long, aes(x = Ranking, y = Rank, group = Gene)) +
  geom_line(aes(color = gene.score), size = 1) +
  geom_point(size = 1) +
  
  # Left labels (forecASD)
  geom_text(data = df_long %>% filter(Ranking == "forecASD"),
            aes(label = Gene), 
            hjust = 1.1, size = 4) +
  
  # Right labels (Deep_MOTIFs)
  geom_text(data = df_long %>% filter(Ranking == "Deep_MOTIFs"),
            aes(label = Gene), 
            hjust = -0.1, size = 4) +
  
  scale_color_manual(name = "SFARI score",  # <-- Adds legend title
                     values = gene.score_colors, 
                     breaks = c("1", "2", "3", "NA")  # explicitly define order in legend
            )+
  scale_y_reverse() +
  labs(title = "(A) Gene ranking between forecASD and Deep-MOTIFs", x = "", y = "Rank") +
  
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "right",
    #legend.title = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 25),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    legend.text = element_text(size = 18),
    
    # Reduce spacing between axis title and plot
    axis.title.y = element_text(margin = margin(r = 5)),

    # Remove extra padding from x axis text
    axis.text.x = element_text(margin = margin(t = 0, b = 0))
  ) +
  
  # Expand plot limits to make room for labels
  scale_x_discrete(expand = expansion(mult = c(0.2, 0.2)))  # Adds space on both sides

ranking_change
```





```{r, message=F, warning=F, eval=F}
library(gridExtra)
all <- grid.arrange(ranking_change,  gene_set_enrichment, nrow=1) 
ggsave(all,filename = paste0("C:\\Users\\hans\\OneDrive - Marquette University\\AI_for_Autism\\Fig\\Gene_Enrichment.pdf"),width = 14,height = 7,dpi = 600)
```




